# Generated by Django 6.0.2 on 2026-02-07 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('country_code', models.CharField(max_length=2)),
                ('country', models.CharField(max_length=255)),
                ('timezone', models.CharField(max_length=255)),
                ('data', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name', 'country'], name='api_city_name_0c7dd7_idx'),
                            models.Index(fields=['latitude', 'longitude'], name='api_city_latitud_ce8d46_idx')],
                'constraints': [models.UniqueConstraint(fields=('name', 'country_code'), name='unique_city')],
            },
        ),
        migrations.CreateModel(
            name='WeatherDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(max_length=255)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.city')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WeatherHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('temperature', models.FloatField()),
                ('precipitation', models.FloatField()),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.weatherdataset')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='weatherdataset',
            index=models.Index(fields=['city', 'start_date', 'end_date'], name='api_weather_city_id_3f9bcc_idx'),
        ),
        migrations.AddConstraint(
            model_name='weatherdataset',
            constraint=models.UniqueConstraint(fields=('city', 'start_date', 'end_date'), name='unique_dataset'),
        ),
        migrations.AddIndex(
            model_name='weatherhour',
            index=models.Index(fields=['dataset', 'timestamp'], name='api_weather_dataset_81ccc0_idx'),
        ),
        migrations.AddConstraint(
            model_name='weatherhour',
            constraint=models.UniqueConstraint(fields=('dataset', 'timestamp'), name='unique_hour'),
        ),
    ]
