# Generated by Django 6.0.2 on 2026-02-07 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weatherhour',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveIndex(
            model_name='city',
            name='api_city_name_0c7dd7_idx',
        ),
        migrations.AddField(
            model_name='weatherdataset',
            name='data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='weatherdataset',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to='api.city'),
        ),
        migrations.AlterField(
            model_name='weatherhour',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hours', to='api.weatherdataset'),
        ),
        migrations.AddIndex(
            model_name='city',
            index=models.Index(fields=['name', 'country_code'], name='api_city_name_ceee99_idx'),
        ),
        migrations.RemoveField(
            model_name='city',
            name='data',
        ),
    ]
