# Generated by Django 6.0.2 on 2026-02-07 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_weatherhour_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherhour',
            name='precipitation',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='weatherhour',
            name='temperature',
            field=models.FloatField(null=True),
        ),
    ]
